Repository indocom/pinus-client, pull requests merged in 2021-01, with the labels that each got.

#67 enhancement: mobile version of home page
  src/pageContent/Home/index.tsx
  src/pageContent/Home/styles.tsx
  tailwind.config.js
Labels: type: enhancement

#57 pages: Add About Us page
  public/assets/backgrounds/about.jpg
  public/assets/images/exco-group.png
  src/components/Text/index.tsx
  src/pageContent/About/index.tsx
  src/pageContent/About/styles.tsx
  src/pages/about/index.tsx
  tailwind.config.js
Labels: type: enhancement

#77 enhancement/admissions mobile
  docs/admissions/after/01.md
  docs/admissions/after/02.md
  docs/admissions/after/03.md
  docs/admissions/after/04.md
  docs/admissions/after/05.md
  docs/admissions/after/06.md
  docs/admissions/after/07.md
  docs/admissions/after/08.md
  docs/admissions/after/09.md
  docs/admissions/after/10.md
  docs/admissions/after/11.md
  docs/admissions/after/12.md
  docs/admissions/after/13.md
  docs/admissions/before/01.md
  docs/admissions/before/02.md
  docs/admissions/before/03.md
  docs/admissions/before/04.md
  docs/admissions/before/05.md
  docs/admissions/before/06.md
  docs/admissions/before/07.md
  docs/admissions/before/08.md
  docs/admissions/before/09.md
  docs/admissions/before/mendaftar-kuliah-di-nus/mendaftar.md
  src/pageContent/Admissions/index.tsx
  src/pageContent/Home/index.tsx
  src/pages/admissions/index.tsx
Labels: type: enhancement

#90 enhancement: mobile for about page
  src/pageContent/About/desktop.tsx
  src/pageContent/About/index.tsx
  src/pageContent/About/mobile.tsx
Labels: priority: high, type: enhancement

#93 Add Events page
  public/assets/backgrounds/events.jpg
  public/assets/images/mkp.jpg
  public/assets/images/nuansa-2.jpg
  public/assets/images/nusantaraku.jpg
  public/assets/images/pinus-ori.jpg
  public/assets/images/popi.jpg
  src/components/Footer/columns.tsx
  src/pageContent/Events/data.ts
  src/pageContent/Events/index.tsx
  src/pageContent/Events/style.ts
  src/pageContent/Events/util.tsx
  src/pages/events/[id].tsx
  src/pages/events/index.tsx
  tailwind.config.js
Labels: WIP: do not merge
